### ISSUE TITLE
Error creating OpenSearch domain: ValidationException: The StartAt time you provided occurs in the past.

### ISSUE THREAD

**Issue by YungBinary** [QinetiQ-Cyber-Intelligence/OpenCTI-Terraform#2]
Hello,

I am running into an issue as seen below. It looks like time_static only runs once, so subsequent deployment attempts cause an error.

```
Error: Error creating OpenSearch domain: ValidationException: The StartAt time you provided occurs in the past. Specify a time in the future.
│ 
│   with module.opensearch.aws_opensearch_domain.this,
│   on modules/opensearch/main.tf line 8, in resource "aws_opensearch_domain" "this":
│    8: resource "aws_opensearch_domain" "this" {
```

**Comment by YungBinary** [comment]
After looking at my `terraform plan` output, I discovered the static time set by the time_static resource was from a day ago. I noticed I can get around the issue by changing the `opensearch_auto_tune.length` variable in `variables.tfvars` to a higher number, like `48h`. Note: This affects the first day that maintenance will start, which in my case is a day from now.

**Comment by ReadyElbow** [comment]
This will occur if you start the Terraform deployment but then pause the deployment process before OpenSearch is deployed. For example, cancelling (`CTRL + C`) `terraform apply` midway.

In the OpenSearch module on line 33, `start_at = timeadd(time_static.this.rfc3339, var.opensearch_auto_tune.length)` involves adding a set number hours to the current time (2h, 48h etc). This current time is, as pointed out, statically defined on the first deployment.

If the Terraform deployment is paused and resumed 2hrs later (the default value), AWS will return an error when Terraform attempts to deploy OpenSearch because the now calculated `start_at` date would be in the past when it expects a future date/time.

Unfortunately, the `maintenance_schedule` code block is required by AWS/Terraform.

I would recommend **either**:
- Deleting the Terraform `module.opensearch.time_static.this` value from the Terraform State file so it is recreated
  - Confirm the correct Terraform resource name first
- Performing a complete `terraform destroy` and then subsequent `terraform apply` to ensure the deployment is run in one go

**Comment by YungBinary** [comment]
> This will occur if you start the Terraform deployment but then pause the deployment process before OpenSearch is deployed. For example, cancelling (`CTRL + C`) `terraform apply` midway.
> 
> In the OpenSearch module on line 33, `start_at = timeadd(time_static.this.rfc3339, var.opensearch_auto_tune.length)` involves adding a set number hours to the current time (2h, 48h etc). This current time is, as pointed out, statically defined on the first deployment.
> 
> If the Terraform deployment is paused and resumed 2hrs later (the default value), AWS will return an error when Terraform attempts to deploy OpenSearch because the now calculated `start_at` date would be in the past when it expects a future date/time.
> 
> Unfortunately, the `maintenance_schedule` code block is required by AWS/Terraform.
> 
> I would recommend **either**:
> 
> * Deleting the Terraform `module.opensearch.time_static.this` value from the Terraform State file so it is recreated
>   
>   * Confirm the correct Terraform resource name first
> * Performing a complete `terraform destroy` and then subsequent `terraform apply` to ensure the deployment is run in one go

Right. Perhaps the default value for the length should be updated as a possible alleviation to anyone else that experiences this issue?

**Comment by ReadyElbow** [comment]
The value though is intended to be the time at which the maintenance schedule (cron job) comes into effect. If you have defined a recurring Cron Job to run every week and you have set the `start_at` value to something like `24h` then you could end up missing your first maintenance period. This might be a frustration for someone else who deploys the solution but this is an edge case.

It could maybe be increased to maximum `6hrs` (let me know your thoughts) but Terraform is not meant to be deployed, paused for a day or so and then continued... Its an end-to-end deployment that you let run from start to finish. If this is done then the issue you have detailed above does not occur; this is very specific to how you have deployed it.

**Comment by ReadyElbow** [comment]
Following on from separate conversation, increased suggested `auto_tune` start from time to 6 hours.
